services:
  svs:
    # image: ghcr.io/kristiankunc/svs-core-sandbox:latest
    build:
      context: ..
      dockerfile: sandbox-env/Dockerfile
    container_name: svs-core
    privileged: true
    restart: no
